export const HOME = "/";
export const COMPANY = "/company";
export const ACCOUNT = "/create-account";
export const LOGIN = "/login";
export const VALIDATE = "/validate";
export const RESET_PASSWORD = "/reset-password";
export const CHANGE_PASSWORD = "/change-password";
export const SETTING = "/setting";
export const SIGNUP = "/sign-up";
export const COMPLETE = "/complete-account";
export const SHOW_ACCOUNT = "/account";
export const FAQ = "/faq";
export const LOGS ="/logs"
